from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.widgets.markers import makeMarker
from datetime import datetime
import pandas as pd
import json
import os
from PIL import Image as PILImage
import base64
from io import BytesIO

class PDFReportGenerator:
    def __init__(self, company_name="Business Reputation Report"):
        self.company_name = company_name
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
        
    def setup_custom_styles(self):
        """Create custom styles for the report"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            alignment=TA_CENTER,
            spaceAfter=30,
            fontName='Helvetica-Bold'
        ))
        
        # Section header style
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=18,
            textColor=colors.HexColor('#764ba2'),
            spaceBefore=20,
            spaceAfter=12,
            fontName='Helvetica-Bold'
        ))
        
        # Problem card style
        self.styles.add(ParagraphStyle(
            name='ProblemCard',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=colors.black,
            leftIndent=10,
            rightIndent=10,
            spaceAfter=6
        ))
        
        # Severity style
        self.styles.add(ParagraphStyle(
            name='SeverityHigh',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.red,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SeverityMedium',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.orange,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SeverityLow',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.green,
            fontName='Helvetica-Bold'
        ))

    def create_header_footer(self, canvas, doc):
        """Add header and footer to each page"""
        canvas.saveState()
        
        # Header
        header_text = f"{self.company_name} - {datetime.now().strftime('%B %d, %Y')}"
        canvas.setFont('Helvetica-Bold', 9)
        canvas.setFillColor(colors.HexColor('#667eea'))
        canvas.drawString(inch, 11 * inch, header_text)
        
        # Footer
        footer_text = f"Page {doc.page} | Generated by Business Reputation Monitor"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.grey)
        canvas.drawString(inch, 0.5 * inch, footer_text)
        
        # Add decorative line
        canvas.setStrokeColor(colors.HexColor('#667eea'))
        canvas.setLineWidth(1)
        canvas.line(inch, 10.75 * inch, 7.5 * inch, 10.75 * inch)
        canvas.line(inch, 0.75 * inch, 7.5 * inch, 0.75 * inch)
        
        canvas.restoreState()

    def create_cover_page(self, story, df, insights):
        """Create an attractive cover page"""
        # Title
        story.append(Spacer(1, 2 * inch))
        story.append(Paragraph(f"{self.company_name}", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Business Reputation Report", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5 * inch))
        
        # Subtitle
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            alignment=TA_CENTER,
            textColor=colors.grey
        )
        story.append(Paragraph(f"Analysis Period: {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
        story.append(Spacer(1, 0.2 * inch))
        
        # Key metrics
        total_reviews = len(df)
        negative_count = len(df[df['sentiment'] == 'Negative'])
        positive_count = len(df[df['sentiment'] == 'Positive'])
        
        metrics_data = [
            ["Total Reviews", "Negative", "Positive", "Neutral"],
            [str(total_reviews), str(negative_count), str(positive_count), str(len(df[df['sentiment'] == 'Neutral']))]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 14),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6'))
        ]))
        
        story.append(metrics_table)
        story.append(Spacer(1, 0.5 * inch))
        
        # Sentiment pie chart
        story.append(Paragraph("Overall Sentiment Distribution", self.styles['SectionHeader']))
        
        # Create pie chart drawing
        drawing = Drawing(400, 200)
        pie = Pie()
        pie.x = 150
        pie.y = 40
        pie.width = 120
        pie.height = 120
        
        sentiment_counts = df['sentiment'].value_counts()
        pie.data = list(sentiment_counts.values)
        pie.labels = list(sentiment_counts.index)
        
        # Color mapping
        pie_colors = {
            'Positive': colors.green,
            'Neutral': colors.orange,
            'Negative': colors.red
        }
        pie.slices.strokeWidth = 0.5
        for i, label in enumerate(pie.labels):
            pie.slices[i].fillColor = pie_colors.get(label, colors.grey)
        
        drawing.add(pie)
        story.append(drawing)
        
        story.append(PageBreak())

    def create_sentiment_section(self, story, df):
        """Create detailed sentiment analysis section"""
        story.append(Paragraph("Sentiment Analysis Results", self.styles['SectionHeader']))
        
        # Summary paragraph
        total = len(df)
        positive = len(df[df['sentiment'] == 'Positive'])
        negative = len(df[df['sentiment'] == 'Negative'])
        neutral = len(df[df['sentiment'] == 'Neutral'])
        sarcasm = df['sarcasm_detected'].sum()
        
        summary_text = f"""
        Based on the analysis of {total} customer reviews, we found that 
        {positive} ({positive/total*100:.1f}%) were positive, {negative} ({negative/total*100:.1f}%) were negative, 
        and {neutral} ({neutral/total*100:.1f}%) were neutral. Additionally, we detected sarcasm in 
        {sarcasm} ({sarcasm/total*100:.1f}%) of the reviews, which indicates subtle customer dissatisfaction 
        that might otherwise go unnoticed.
        """
        
        story.append(Paragraph(summary_text, self.styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Sentiment scores table
        story.append(Paragraph("Sentiment Score Distribution", self.styles['SectionHeader']))
        
        # Create sentiment scores table
        score_data = [["Metric", "Average Score", "Range"]]
        
        if 'sentiment_negative_score' in df.columns:
            score_data.append([
                "Negative Sentiment",
                f"{df['sentiment_negative_score'].mean():.3f}",
                f"{df['sentiment_negative_score'].min():.3f} - {df['sentiment_negative_score'].max():.3f}"
            ])
            score_data.append([
                "Neutral Sentiment",
                f"{df['sentiment_neutral_score'].mean():.3f}",
                f"{df['sentiment_neutral_score'].min():.3f} - {df['sentiment_neutral_score'].max():.3f}"
            ])
            score_data.append([
                "Positive Sentiment",
                f"{df['sentiment_positive_score'].mean():.3f}",
                f"{df['sentiment_positive_score'].min():.3f} - {df['sentiment_positive_score'].max():.3f}"
            ])
        
        score_table = Table(score_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#764ba2')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6'))
        ]))
        
        story.append(score_table)
        story.append(Spacer(1, 0.3 * inch))

    def create_insights_section(self, story, insights):
        """Create AI-powered insights section"""
        story.append(Paragraph("AI-Powered Insights", self.styles['SectionHeader']))
        story.append(Paragraph("Based on the analysis of negative reviews, our AI has identified the following key issues:",
                              self.styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Create problem-solution cards
        for i, (problem, suggestion, severity) in enumerate(zip(
            insights['problems'], 
            insights['suggestions'], 
            insights.get('severity', ['Medium']*len(insights['problems']))
        ), 1):
            # Problem header with severity
            severity_style = f'Severity{severity}'
            story.append(Paragraph(f"<b>Problem {i}: {problem}</b>", self.styles['SectionHeader']))
            story.append(Paragraph(f"<b>Severity:</b> {severity}", self.styles[severity_style]))
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(f"<b>Suggested Solution:</b> {suggestion}", self.styles['ProblemCard']))
            story.append(Spacer(1, 0.2 * inch))
            
            # Add a light separator
            story.append(Spacer(1, 0.1 * inch))
        
        story.append(Spacer(1, 0.3 * inch))

    def create_recommendations_section(self, story, insights):
        """Create actionable recommendations section"""
        story.append(Paragraph("Actionable Recommendations", self.styles['SectionHeader']))
        
        # Create checklist-style recommendations
        recommendations = []
        for problem, suggestion, severity in zip(
            insights['problems'],
            insights['suggestions'],
            insights.get('severity', ['Medium']*len(insights['problems']))
        ):
            priority = "🔴 HIGH" if severity == "High" else "🟡 MEDIUM" if severity == "Medium" else "🟢 LOW"
            recommendations.append(f"{priority} - {suggestion}")
        
        for i, rec in enumerate(recommendations, 1):
            story.append(Paragraph(f"{i}. {rec}", self.styles['Normal']))
            story.append(Spacer(1, 0.1 * inch))
        
        story.append(Spacer(1, 0.2 * inch))
        
        # Implementation timeline
        story.append(Paragraph("Implementation Timeline", self.styles['SectionHeader']))
        
        timeline_data = [
            ["Timeframe", "Action Items"],
            ["Week 1-2", "Address High severity issues immediately"],
            ["Week 3-4", "Implement solutions for Medium severity problems"],
            ["Week 5-6", "Review and optimize based on customer feedback"],
            ["Ongoing", "Monitor new reviews and adjust strategy"]
        ]
        
        timeline_table = Table(timeline_data, colWidths=[1.5*inch, 4*inch])
        timeline_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige)
        ]))
        
        story.append(timeline_table)

    def create_sarcasm_section(self, story, df):
        """Create sarcasm detection section"""
        sarcasm_reviews = df[df['sarcasm_detected'] == True]
        
        if len(sarcasm_reviews) > 0:
            story.append(Paragraph("Sarcasm Detection Analysis", self.styles['SectionHeader']))
            story.append(Paragraph(f"We detected sarcasm in {len(sarcasm_reviews)} reviews. These often indicate deeper issues that customers express indirectly:",
                                  self.styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))
            
            # Show examples of sarcastic reviews
            story.append(Paragraph("Examples of Detected Sarcasm:", self.styles['SectionHeader']))
            
            for idx, (_, row) in enumerate(sarcasm_reviews.head(3).iterrows(), 1):
                review_text = row['full_text'][:200] + "..." if len(row['full_text']) > 200 else row['full_text']
                story.append(Paragraph(f"<b>Example {idx}:</b> \"{review_text}\"", self.styles['ProblemCard']))
                story.append(Spacer(1, 0.1 * inch))
            
            story.append(Spacer(1, 0.3 * inch))

    def create_appendix(self, story, df):
        """Create appendix with sample reviews"""
        story.append(Paragraph("Appendix: Sample Reviews", self.styles['SectionHeader']))
        
        # Show sample of negative reviews
        story.append(Paragraph("Sample Negative Reviews:", self.styles['SectionHeader']))
        negative_reviews = df[df['sentiment'] == 'Negative'].head(5)
        
        for idx, (_, row) in enumerate(negative_reviews.iterrows(), 1):
            story.append(Paragraph(f"<b>Review {idx}:</b>", self.styles['Normal']))
            review_text = row['full_text'][:300] + "..." if len(row['full_text']) > 300 else row['full_text']
            story.append(Paragraph(f"\"{review_text}\"", self.styles['ProblemCard']))
            story.append(Spacer(1, 0.1 * inch))
        
        story.append(Spacer(1, 0.2 * inch))
        
        # Show sample of positive reviews
        story.append(Paragraph("Sample Positive Reviews:", self.styles['SectionHeader']))
        positive_reviews = df[df['sentiment'] == 'Positive'].head(3)
        
        for idx, (_, row) in enumerate(positive_reviews.iterrows(), 1):
            story.append(Paragraph(f"<b>Review {idx}:</b>", self.styles['Normal']))
            review_text = row['full_text'][:300] + "..." if len(row['full_text']) > 300 else row['full_text']
            story.append(Paragraph(f"\"{review_text}\"", self.styles['ProblemCard']))
            story.append(Spacer(1, 0.1 * inch))

    def generate_report(self, filename="business_reputation_report.pdf"):
        """Generate complete PDF report"""
        print("📊 Loading data...")
        
        # Load data
        try:
            df = pd.read_csv('analyzed_reviews_optimized.csv')
            with open('insights.json', 'r', encoding='utf-8') as f:
                insights = json.load(f)
        except Exception as e:
            print(f"❌ Error loading data: {e}")
            return False
        
        print(f"✅ Loaded {len(df)} reviews and insights")
        
        # Create PDF document
        doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        # Build story
        story = []
        
        # Add cover page
        self.create_cover_page(story, df, insights)
        
        # Add sentiment analysis section
        self.create_sentiment_section(story, df)
        
        # Add insights section
        self.create_insights_section(story, insights)
        
        # Add recommendations section
        self.create_recommendations_section(story, insights)
        
        # Add sarcasm section
        self.create_sarcasm_section(story, df)
        
        # Add appendix
        self.create_appendix(story, df)
        
        # Generate PDF
        print("📝 Generating PDF report...")
        doc.build(story, onFirstPage=self.create_header_footer, onLaterPages=self.create_header_footer)
        
        print(f"✅ PDF report generated successfully: {filename}")
        return True

def generate_quick_report():
    """Quick function to generate report from existing files"""
    generator = PDFReportGenerator(company_name="Business Reputation Report")
    success = generator.generate_report("business_insights_report.pdf")
    
    if success:
        print("\n🎉 Report is ready! Check 'business_insights_report.pdf'")
        return "business_insights_report.pdf"
    else:
        print("❌ Failed to generate report")
        return None

if __name__ == "__main__":
    print("🚀 PDF Report Generator")
    print("="*50)
    generate_quick_report()